python main.py --cfg ./config/CIFAR100_LT/balanced_softmax_imba100_1.yaml --test --save_feat 'train'
python main.py --cfg ./config/CIFAR100_LT/balanced_softmax_imba100_1.yaml --test --save_feat 'val'
python main.py --cfg ./config/CIFAR100_LT/balanced_softmax_imba100_2.yaml --test --save_feat 'train'
python main.py --cfg ./config/CIFAR100_LT/balanced_softmax_imba100_2.yaml --test --save_feat 'val'
python main.py --cfg ./config/CIFAR100_LT/balanced_softmax_imba100_3.yaml --test --save_feat 'train'
python main.py --cfg ./config/CIFAR100_LT/balanced_softmax_imba100_3.yaml --test --save_feat 'val'