python main.py --cfg ./config/CIFAR10_LT/balms_imba100_1.yaml --test --save_feat 'train'
python main.py --cfg ./config/CIFAR10_LT/balms_imba100_1.yaml --test --save_feat 'val'
python main.py --cfg ./config/CIFAR10_LT/balms_imba100_2.yaml --test --save_feat 'train'
python main.py --cfg ./config/CIFAR10_LT/balms_imba100_2.yaml --test --save_feat 'val'
python main.py --cfg ./config/CIFAR10_LT/balms_imba100_3.yaml --test --save_feat 'train'
python main.py --cfg ./config/CIFAR10_LT/balms_imba100_3.yaml --test --save_feat 'val'
python main.py --cfg ./config/CIFAR10_LT/balms_imba100_4.yaml --test --save_feat 'train'
python main.py --cfg ./config/CIFAR10_LT/balms_imba100_4.yaml --test --save_feat 'val'